-- Insert sample products to fix 406 errors
-- These match the products in src/data/products.ts

INSERT INTO public.products (
  name, 
  description, 
  price, 
  category, 
  image_url, 
  stock_quantity,
  warranty,
  shipping_info,
  return_policy,
  return_days,
  specifications,
  weight,
  dimensions,
  sku,
  brand,
  tags,
  discount_percent,
  original_price
) VALUES 
(
  'NanoShield Ceramic Coating',
  'Advanced nano-ceramic coating that provides up to 5 years of protection. Self-healing properties repair minor scratches with heat activation.',
  89.99,
  'exterior',
  'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&h=600&fit=crop',
  100,
  '5 Year Manufacturer Warranty',
  'Free shipping on orders over $50. Ships in 1-2 business days.',
  'Hassle-free returns',
  30,
  '{"Volume": "50ml", "Coverage": "Up to 2 vehicles", "Durability": "5 years", "Application": "Professional/Advanced DIY", "Cure Time": "24-48 hours"}',
  '0.3 lbs',
  '3 x 2 x 1.5 inches',
  'AC-NSCC-50',
  'AutoCure',
  '{"premium", "best-seller", "ceramic"}',
  0,
  NULL
),
(
  'HyperFoam Car Shampoo',
  'Ultra-thick foam formula that clings to surfaces for maximum cleaning power. pH balanced and safe for all coatings.',
  29.99,
  'exterior',
  'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&h=600&fit=crop',
  200,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"Volume": "1000ml", "pH Level": "7.0 (Neutral)", "Dilution Ratio": "1:400", "Scent": "Fresh Citrus", "Safe For": "All paint types"}',
  '2.2 lbs',
  '9 x 3 x 3 inches',
  'AC-HFS-1L',
  'AutoCure',
  '{"best-seller", "wash", "value"}',
  14,
  34.99
),
(
  'CrystalWax Pro Polish',
  'Premium carnauba and synthetic hybrid wax that delivers a mirror-like finish with deep gloss enhancement.',
  54.99,
  'exterior',
  'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop',
  150,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"Volume": "250ml", "Type": "Carnauba/Synthetic Hybrid", "Durability": "3 months", "Application": "Hand or DA polisher", "Finish": "Deep gloss"}',
  '0.6 lbs',
  '4 x 2 x 2 inches',
  'AC-CWP-250',
  'AutoCure',
  '{"premium", "wax", "gloss"}',
  0,
  NULL
),
(
  'UltraPlush Microfiber Set',
  'Set of 6 premium 600 GSM microfiber towels. Edgeless design prevents scratching on all surfaces.',
  29.99,
  'tools',
  'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
  300,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"GSM": "600", "Quantity": "6 towels", "Size": "16x16 inches", "Edge Type": "Edgeless ultrasonic cut", "Color": "Gray"}',
  '0.8 lbs',
  '8 x 6 x 3 inches',
  'AC-UPMF-6',
  'AutoCure',
  '{"best-seller", "tools", "microfiber"}',
  0,
  NULL
),
(
  'TireBlack Elite Cleaner',
  'Professional-grade tire cleaner and dressing that restores deep black finish with a satin sheen.',
  24.99,
  'exterior',
  'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop',
  250,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"Volume": "500ml", "Finish": "Satin", "Application": "Spray or applicator", "Drying Time": "10 minutes", "Durability": "2 weeks"}',
  '1.2 lbs',
  '8 x 3 x 3 inches',
  'AC-TBE-500',
  'AutoCure',
  '{"tires", "dressing", "new"}',
  0,
  NULL
),
(
  'CockpitCare Interior Detailer',
  'All-in-one interior cleaner and protectant. Anti-static formula repels dust and provides UV protection.',
  39.99,
  'interior',
  'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&h=600&fit=crop',
  180,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"Volume": "500ml", "Surfaces": "Dashboard, trim, screens", "Finish": "Matte/OEM", "Scent": "New Car", "Anti-Static": "Yes"}',
  '1.1 lbs',
  '8 x 3 x 3 inches',
  'AC-CCI-500',
  'AutoCure',
  '{"interior", "dashboard", "new"}',
  0,
  NULL
),
(
  'LeatherLux Conditioner',
  'Premium leather conditioner that nourishes and protects. Prevents cracking and fading while restoring suppleness.',
  44.99,
  'interior',
  'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&h=600&fit=crop',
  120,
  '1 Year Warranty',
  'Free shipping on orders over $50',
  'Hassle-free returns',
  30,
  '{"Volume": "250ml", "Leather Types": "All automotive leather", "Finish": "Natural matte", "Scent": "Natural leather", "UV Protection": "Yes"}',
  '0.6 lbs',
  '4 x 2 x 2 inches',
  'AC-LLC-250',
  'AutoCure',
  '{"premium", "leather", "interior"}',
  0,
  NULL
),
(
  'ProDetail Ultimate Kit',
  'The complete detailing kit for enthusiasts. Includes shampoo, polish, wax, interior cleaner, microfiber towels, and applicators.',
  199.99,
  'kits',
  'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop',
  50,
  '2 Year Warranty',
  'Free shipping on all kits',
  'Hassle-free returns',
  30,
  '{"Products Included": "12", "Carry Case": "Yes, premium", "Guide Book": "Yes, 20 pages", "Skill Level": "Beginner to Pro", "Value Savings": "25% vs individual"}',
  '8.5 lbs',
  '18 x 12 x 8 inches',
  'AC-PDK-ULT',
  'AutoCure',
  '{"premium", "kit", "best-seller", "value"}',
  0,
  NULL
)
ON CONFLICT (name) DO NOTHING;

SELECT 'Sample products added successfully!' as status;
